### ISSUE TITLE
Test on Mac OS

### ISSUE THREAD

**Issue by OxyDeadbeef** [plopgrizzly/whoami#6]
# System Support Request
Make sure that the library works on Mac OS.

* Fix Getting OS Name
* Fix Getting Computer Name
* Fix Getting Environment

**Comment by cygnus9** [comment]
I just had someone test it on a mac, and at least it compiles now. Getting the username also works. Getting the OS or computer name fails at runtime and getting the env simply returns "unknown".

**Comment by OxyDeadbeef** [comment]
Next time I use a Mac, I'll try and fix it.

**Comment by OxyDeadbeef** [comment]
Update: I finally got around to testing it on a Mac and I fixed getting the OS name, computer name and environment.  `whoami` 0.4 is out on [crates.io](https://crates.io) with the changes.

**Comment by cygnus9** [comment]
Cool, thanks.
